env:
  node: true
  browser: true
  es2020: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  "no-console": "off",
  "import/extensions": [0, { "js": "always"}],
  "no-await-in-loop": "off"
}
