env:
  node: true
  browser: true
  es2021: true
extends: [
  "airbnb-base"
]
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  "no-console": 0,
  "import/extensions": [0, { "js": "always"}],
  "no-await-in-loop": 0,
  "brace-style": [2, "stroustrup"],
  "import/no-unresolved": "off",
  "no-constant-condition": "off"
}
